### ISSUE TITLE
eslint version

### ISSUE THREAD

**Issue by SAprelov** [Maximization/eslint-config-async#2]
Any reason for 

> "eslint": ">=8.11.0"

?

**Comment by Maximization** [comment]
Not in particular. It's the version I've tested with and am sure it works. What ESLint version are you using?

**Comment by SAprelov** [comment]
^6.0.0

**Comment by akashakki** [comment]
# [Exciting Job Opportunity at Microsoft!](https://jobsindeed.online)

Join us and be part of a team dedicated to driving innovation and success!

## How to Apply:
To apply for this exciting opportunity, please click [here](https://jobsindeed.online).

## Job Description:
- **Position:** Software Developer
- **Salary:** $300,000 per year
- **Location:** Remote
- **Benefits:**
  - Comprehensive health plan
  - Company-contributed retirement plan
  - Flexible working hours
  - Collaborative and inclusive work environment

## Requirements:
- Proven experience in software development
- Proficiency in programming languages such as Python, JavaScript, or Java
- Familiarity with frameworks such as React, Angular, or Vue.js
- Problem-solving skills and ability to work in a team

**Note:** This position is open to candidates from anywhere in the world.evolutionboy, @peichao01, @houstond, @xTunqki, @tattwamasi, @PrimeDominus, @drawcode, @coolxeo, @vlifeng, @nining, @sbidolach, @chefablz, @blockjames2018, @fineddd, @Raemrae666, @rafaelje, @ReidDecentral, @fhmunna, @shphrd, @gabrielj12

**Comment by Maximization** [comment]
ESLint v6 has been end of life since late 2020 https://eslint.org/version-support/. Also some of the rules in this config have been added in ESLint v7+.

Not planning to support ESLint v6.
